@startuml
hide methods

class User <<Entity>> {
    username: String
    email: String
    password: String

    messages: List<Message>
    roles: Collection<Role>
}

class Message<<Entity>>{
    text: String
    creation: LocalDateTime

    user: User
}

class Role<<Entity>>{
    name: String

    users: Collection<User>
    privileges: Collection<Privilege>
}

class Privilege<<Entity>>{
    name: String

    roles: Collection<Role>
}

User "1" *-down-o "n" Message
User "n" o-o "m" Role
Role "n" o-down-o "m" Privilege

@enduml