@startuml
hide methods

class User <<Entity>> {
    username: String
    email: String
    password: String
    googleId: String

    messages: List<Message>
    roles: Collection<Role>
}

class Message<<Entity>>{
    text: String
    creation: LocalDateTime

    user: User
}

class Role<<Entity>>{
    name: String

    users: Collection<User>
}

User "1" *-down-o "n" Message
User "n" o-o "m" Role

@enduml